services:
  api:
    container_name: phonebook-api-c
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      ./src/.env
    ports:
      ["8000:8000"]
    depends_on:
      - postgres
    
  
  postgres:
    container_name: postgres-db-c
    image: postgres:latest
    restart: always
    env_file:
      ./src/.env
    ports:
      ["5432:5432"]
    volumes:
      - ./db_scripts/db_create_tables.sql:/docker-entrypoint-initdb.d/db_create_tables.sql
      - db_data:/var/lib/postgres/data
  

volumes:
  db_data:


